# -*- coding: utf-8 -*-
"""Newsjackking Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-bjWvRVVCpt_ek3qkqd5BONNyr2cWp8
"""



import json
import logging
from datetime import datetime
import feedparser
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

class RegulatoryIngestionEngine:
    def __init__(self, bls_api_key: str = None):
        self.bls_api_key = bls_api_key
        self.normalized_signals = []

    def _add_signal(self, source: str, category: str, title: str, url: str, date: str, raw_content: str = ""):
        self.normalized_signals.append({
            "source": source,
            "category": category,
            "title": title,
            "url": url,
            "published_at": date,
            "content": raw_content[:500],  # Truncated sample
            "ingested_at": datetime.utcnow().isoformat()
        })

    # A. CMS via Federal Register API
    def fetch_cms_updates(self):
        logging.info("Fetching CMS Federal Register updates...")
        url = (
            "https://www.federalregister.gov/api/v1/documents.json"
            "?conditions[agencies][]=centers-for-medicare-medicaid-services"
            "&per_page=5&order=newest"
        )
        try:
            res = requests.get(url, timeout=10).json()
            for doc in res.get("results", []):
                self._add_signal(
                    source="CMS / Federal Register",
                    category="Policy & Regulatory",
                    title=doc.get("title"),
                    url=doc.get("html_url"),
                    date=doc.get("publication_date"),
                    raw_content=doc.get("abstract", "")
                )
        except Exception as e:
            logging.error(f"Error fetching CMS updates: {e}")

    # B. Healthcare Dive & Becker's via RSS
    def fetch_rss_feeds(self):
        logging.info("Fetching RSS industry news feeds...")
        rss_urls = {
            "Healthcare Dive": "https://www.healthcaredive.com/feeds/news/",
            "HHS OIG News": "https://oig.hhs.gov/rss/newsroom.xml"
        }
        for source_name, feed_url in rss_urls.items():
            try:
                feed = feedparser.parse(feed_url)
                for entry in feed.entries[:5]:
                    self._add_signal(
                        source=source_name,
                        category="Industry & Operational Trends",
                        title=entry.title,
                        url=entry.link,
                        date=entry.get("published", datetime.utcnow().isoformat()),
                        raw_content=entry.get("summary", "")
                    )
            except Exception as e:
                logging.error(f"Error fetching RSS for {source_name}: {e}")

    # C. BLS Wage & Labor Data via Public API
    def fetch_bls_labor_data(self):
        logging.info("Fetching BLS labor series metrics...")
        url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
        headers = {"Content-Type": "application/json"}
        # Example series IDs: Average Hourly Earnings for Nursing Facilities (CES6562311003)
        payload = json.dumps({
            "seriesid": ["CES6562311003"],
            "startyear": "2025",
            "endyear": "2026",
            **({"registrationkey": self.bls_api_key} if self.bls_api_key else {})
        })
        try:
            res = requests.post(url, data=payload, headers=headers, timeout=10).json()
            if res.get("status") == "REQUEST_SUCCEEDED":
                for series in res["Results"]["series"]:
                    s_id = series["seriesID"]
                    for data in series["data"][:1]:  # Latest data point
                        self._add_signal(
                            source="Bureau of Labor Statistics",
                            category="Labor Market",
                            title=f"BLS Series {s_id} Metric Update: {data['value']}",
                            url="https://www.bls.gov/data/",
                            date=f"{data['year']}-{data['period']}",
                            raw_content=f"Period: {data['periodName']} {data['year']}, Value: {data['value']}"
                        )
        except Exception as e:
            logging.error(f"Error fetching BLS metrics: {e}")

    def run_all(self):
        self.fetch_cms_updates()
        self.fetch_rss_feeds()
        self.fetch_bls_labor_data()
        return self.normalized_signals

if __name__ == "__main__":
    engine = RegulatoryIngestionEngine()
    signals = engine.run_all()
    print(json.dumps(signals, indent=2))

import requests


def generate_executive_digest(signals):
    """
    Transforms ingested signals into a formatted Executive Digest.
    """
    if not signals:
        return "No new intelligence signals retrieved."

    # Group signals by category
    categorized = {}
    for sig in signals:
        cat = sig.get("category", "General Updates")
        categorized.setdefault(cat, []).append(sig)

    # Build Markdown string
    digest_md = "## 📢 Executive Intelligence Signal Digest\n"
    digest_md += f"*Generated on: {signals[0].get('ingested_at', 'N/A')[:10]}*\n\n---\n\n"

    for category, items in categorized.items():
        digest_md += f"### 📌 {category}\n"
        for item in items[:3]:  # Top 3 items per category
            digest_md += f"* **[{item['title']}]({item['url']})**\n"
            digest_md += f"  > *Source: {item['source']} | Date: {item['published_at'][:10]}*\n"
            if item.get("content"):
                digest_md += f"  > {item['content'][:150]}...\n"
            digest_md += "\n"

    return digest_md

# ----------------------------------------------------------------
# Option A: Display inside Colab Notebook
# ----------------------------------------------------------------
def display_digest(digest_md):
    print(digest_md)

# ----------------------------------------------------------------
# Option B: Push directly to Slack via Webhook (Optional)
# ----------------------------------------------------------------
def send_to_slack(digest_md, webhook_url):
    payload = {"text": digest_md}
    response = requests.post(webhook_url, json=payload)
    if response.status_code == 200:
        print("✅ Alert successfully sent to Slack!")
    else:
        print(f"❌ Failed to send to Slack: {response.status_code}")

# ----------------------------------------------------------------
# Execution Example
# ----------------------------------------------------------------
# Assuming 'signals' came from your Step 1 run:
# signals = engine.run_all()

digest = generate_executive_digest(signals)

# 1. Render in Colab
def display_digest(digest_md):
    print(digest_md)

# 2. (Optional) Uncomment to send to Slack:
# SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
# send_to_slack(digest, SLACK_WEBHOOK_URL)

import os
from datetime import datetime
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive')

def save_digest_to_drive(digest_md):
    # 2. Define directory path in Google Drive
    drive_folder = '/content/drive/My Drive/Intelligence_Reports'
    os.makedirs(drive_folder, exist_ok=True)

    # 3. Create a timestamped filename
    today_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"Executive_Digest_{today_str}.md"
    file_path = os.path.join(drive_folder, filename)

    # 4. Write the Markdown content to file
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(digest_md)

    print(f"✅ Report successfully saved to Drive: {file_path}")

# Run the save function
save_digest_to_drive(digest)

# 1. Install dependencies

# 2. Instantiate and run Ingestion Engine (Step 1)
engine = RegulatoryIngestionEngine()
raw_signals = engine.run_all()

# 3. Format and render Executive Digest (Step 3)
digest_output = generate_executive_digest(raw_signals)
def display_digest(digest_md):
    print(digest_md)
